apiVersion: v1
kind: Pod
metadata:
  name: cluster-test
spec:
  nodeSelector:
    nodeType: clustertest
  restartPolicy: Never
  serviceAccountName: clustertest
  tolerations:
  - key: "clustertest"
    operator: "Exists"
    effect: "NoSchedule"
  containers:
    - name: main
      image: 853397791086.dkr.ecr.us-west-2.amazonaws.com/libra_cluster_test:kush_cd1d6df1
      imagePullPolicy: Always
      env:
      - name: RUST_BACKTRACE
        value: "1"
      - name: RUST_LOG
        value: "debug"
      command:
      - cluster-test
      - --run=bench
      - --k8s-fullnodes-per-validator=0
      - --k8s-num-validators=100
#      - --workers-per-ac=200
#      - --accounts-per-client=1
#      - --wait-millis=65
#      - --burst=1
